name: hoge
description: foobar
inputs:
  dir:
    description: baz
    required: true
outputs:
  diff:
    description: bbb
    value: ${{ steps.hogehoge.outputs.diff }}

runs:
  using: composite
  steps:
    - uses: technote-space/get-diff-action@v5
      id: hogehoge
      with:
        PATTERNS: |
          ${{ inputs.dir }}/**/*
    - name: yyyy
      run: echo ${{ steps.hogehoge.outputs.diff }}
      shell: bash
    - name: xxxx
      run: echo ${{ inputs.dir }}
      shell: bash
