name: hoge
description: foobar
inputs:
  dir:
    description: baz
    required: true
outputs:
  diff:
    description: bbb
    value: ${{ steps.hagehage.outputs.diff }}

runs:
  using: composite
  steps:
    - uses: technote-space/get-diff-action@v5
      id: hogehoge
      with:
        PATTERNS: |
          ${{ inputs.dir }}/**/*
    - name: xxx
      id: hagehage
      run: echo "::set-output name=diff::${{ steps.hogehoge.outputs.diff }}"
      run: echo "::set-output name=diff::$(echo $RANDOM)"
